config/routes.rb
Rigli::Application.routes.draw do
  devise_for :users

  resources :rigs
  match 'my-rigs' => 'rigs#my_rigs'
  match ':surl' => 'rigs#redirect'

  root :to => 'rigs#new'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :count, :note, :short_url, :target
  has_one :short, as: :shortable
  belongs_to :rig
  validates :target, :presence => true
  before_create :normalize_target

  private
   def normalize_target
    self.target = "http://" + self.target unless URI(self.target).absolute?
    end
end

app/models/rig.rb
class Rig < ActiveRecord::Base
  attr_accessible :description, :name, :links_attributes
  has_one :short, as: :shortable
  belongs_to :user
  validates :name, :presence => true
  has_many :links

  accepts_nested_attributes_for :links
end

app/models/short.rb
class Short < ActiveRecord::Base
  attr_accessible :surl
  belongs_to :shortable, polymorphic: true
  before_create :generate_surl

  def increment_count
    self.count += 1
  end

  def add_content
    if self.shortable_type == "Link"
      return URI(self.shortable.target).host
    else
      return self.shortable.name
    end
  end

  private
   def generate_surl
    self.surl = rand(36**6).to_s(36)
    if self.class.find_by_surl(surl)
      generate_surl
    else
      surl
    end
   end
end

app/models/shortened_url.rb
class Shortened_url < ActiveRecord::Base
  attr_accessible :shortened_object_id, :type, :surl
  belongs_to :shortened_object, polymorphic: true
  before_create :generate_surl

  private
   def generate_surl
    self.surl = rand(36**6).to_s(36)
    if self.class.find_by_surl(surl)
      generate_surl
    else
      surl
    end
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :rigs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rigs_controller.rb
class RigsController < ApplicationController

  def new
    @rig = Rig.new
    @rig.links.build if @rig.links.empty?
  end

  def create
    @rig = Rig.create(params[:rig])
    @rig.user = current_user
    @rig.short = Short.create
    @rig.links.each { |link| link.short = Short.create }
    if @rig.save
      flash[:notice] = "Successfully created a rig!"
      redirect_to @rig
    else
      errors = @rig.errors.full_messages.join("</br>")
      flash.now['error'] = errors
      render :action => :new
    end
  end

  def destroy
    @rig = Rig.find(params[:id])
    flash[:success] = "Rig destroyed"
  end

  def index
    @shorts = Short.find(:all, order: "count")
  end

  def my_rigs
    @rigs = current_user.rigs
  end

  def update
    if @rig.update_attributes(params[:user])
      flash[:success] = "Rig updated!"
      redirect_to @user
    else
      render "edit"
    end
  end

  def show
    @rig = Rig.find(params[:id])
  end

  def redirect
    @short = Short.find_by_surl!(params[:surl])
    @short.increment_count
    @short.save
    if @short.shortable_type == "Rig"
      @rig = @short.shortable
      redirect_to @rig
    elsif @short.shortable_type == "Link"
      redirect_to @short.shortable.target
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rig_helper.rb
module RigHelper
end

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %title= content_for?(:title) ? yield(:title) : "rigli"
    %meta(name="description" content="")
    %meta(name="author" content="")
    = csrf_meta_tags
    = yield(:head)
    = stylesheet_link_tag "application", :media => "all"

    :css
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }


    /[if lt IE 9]
      %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")

    %link(rel="shortcut icon" href="images/favicon.ico")
    %link(rel="apple-touch-icon" href="images/apple-touch-icon.png")
    %link(rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png")
    %link(rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png")

  %body

    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "Rig<li>", :root, class: "brand"
          %ul.nav
            %li
              = link_to "Popular", rigs_path
          %ul.nav.pull-right
            - if user_signed_in?
              %ul.nav.nav-pills
                %li#menu1.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#menu1"}
                    My Account
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "My Rigs", "../my-rigs"
                    %li
                      = link_to "Log Out", destroy_user_session_path, :method => :delete
            - else
              %li.nav-item.main-link
                = link_to "Log In", new_user_session_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, msg.html_safe, :class =>"#{name}", :id => "flash_#{name}"

    .content-page.container
      .row
        .span11
          = yield

    .container
      %footer{role: "contentinfo"}
        %p
          Rig.li Copyright &copy; 2012. All Rights Reserved.

    = javascript_include_tag "application"
    = yield :body_end

app/views/rigs/_link.html.haml
= f.simple_fields_for :links do |links_form|
  = links_form.input :target

app/views/rigs/index.html.haml
%p
  %ul
  - @shorts.each do |short|
    %li
      = short.count
      = link_to HOST[7..-1]+short.surl, HOST+short.surl
      = short.add_content

app/views/rigs/my_rigs.html.haml
%p
  %ul
  - @rigs.each do |rig|
    %li
      = rig.name
      = link_to HOST[7..-1]+rig.short.surl, HOST+rig.short.surl
      = rig.short.count

app/views/rigs/new.html.haml
%p Welcome to Rig.li!
%p This is the landing page

= simple_form_for @rig, :html => {:class => 'form-horizontal'} do |f|
  = f.input :name
  = f.input :description
  .links
    = render :partial => 'link', :collection => @rig.links, :locals => { :f => f }
  = f.button :submit

app/views/rigs/show.html.haml
%p Your Rig is ready!

= @rig.name
= link_to HOST[7..-1]+@rig.short.surl, HOST+@rig.short.surl
%p
= @rig.description
%P

  %ul
  - @rig.links.each do |link|
    %li
      = link_to HOST[7..-1]+link.short.surl, HOST+link.short.surl
      = link.target
      = link.note